title: <killergerbah>
email: kgerbil@gmail.com
description: >-
  My name is R-J. I like creating stuff and having thoughts about things.
baseurl: ""
url: ""
github_username:  killergerbah

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima@6b9b78dad3e5c9f733c901e10287465735b36169

minima:
  skin: dark
  social_links:
    - platform: github
      user_url: "https://github.com/killergerbah"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/raphael-joel-lim-a1003b5b"
